### ISSUE TITLE
sync: enriching profiles never re-enrich — --full-refresh doesn't clear _enriched_at, so stale detail content is permanent

### ISSUE THREAD

**Issue by siddharth-bhansali** [picahq/cli#174]
## Summary

For a sync profile that declares `enrich`, each record's detail endpoint is fetched **exactly once, ever**. If the upstream detail content later changes, there is no supported way to refresh it — including `--full-refresh`, which is the command a user would reasonably reach for.

## Why

Phase 2 selects only never-enriched rows (`src/lib/memory/sync/enrich.ts:260`):

```sql
SELECT * FROM "<table>" WHERE "<tsField>" IS NULL
```

and stamps `_enriched_at` on every row it processes. Nothing in the codebase ever clears that stamp:

```
$ grep -rn "_enriched_at\|timestampField" src/ | grep -iE "clear|reset|= NULL"
(no matches)
```

`--full-refresh` does not help. It re-pulls every record from the list endpoint (`runner.ts:260`, `sinceDate = null`) and reconciles by deleting rows that no longer exist upstream (`runner.ts:693`, `DELETE … WHERE id NOT IN (SELECT id FROM _seen_ids)`), but **surviving rows keep their stamp** — the phase-1 SQLite write is `INSERT … ON CONFLICT DO UPDATE SET` over only the columns it supplies (`db.ts:247`), and `_enriched_at` isn't one of them. So phase 2 sees zero unenriched rows and makes zero detail calls.

Verified empirically: after a full refresh, `_enriched_at` is unchanged on every surviving row and the detail endpoint is called 0 times.

## Impact

Affects the three shipped enriching profiles — `gmail/gmailThreads`, `fathom/meetings`, and any user profile with `enrich`.

A Gmail thread that gains ten new messages after its first sync keeps the body it had on day one. `mem search` and `mem find-by-key` then serve stale detail content indefinitely, with no signal that it is stale. The list-level fields (`snippet`, `historyId`, labels) *do* keep refreshing, so the record looks live while the enriched half is frozen — which is arguably worse than being obviously stale.

This is **pre-existing**, not introduced by #167. It became more visible there: #167 fixed the list phase silently *overwriting* enriched payloads with the thin list shape, so "re-run the sync to repair it" no longer does anything at all. The current workaround is undocumented and blunt:

```bash
rm .one/sync/data/<platform>.db   # forces a full re-enrich of everything
```

## Why it wasn't fixed in #167

Clearing the stamp is one line, and that's the trap — it re-fans-out the **entire** detail endpoint for every record on the next run. For a large mailbox that's thousands of API calls, subject to per-platform rate limits (`enrichPhase` already has shared-backoff machinery for exactly this reason). Making `--full-refresh` silently do that would turn a routine command into an expensive, potentially rate-limit-tripping operation. That's a product decision, not a drive-by fix.

## Options

1. **`--re-enrich` flag** on `sync run` — explicit, opt-in, clears the stamp before phase 2. Cheapest to build, and the cost is visible in the command the user typed.
2. **Fingerprint-driven re-enrich** — clear the stamp when a designated list field moves (`historyId` for Gmail, `updated_at` elsewhere), via a per-profile `enrich.invalidateOn` path. Correct behaviour by default and cheap in API calls, but needs a sensible per-platform default and does nothing for platforms with no such field.
3. **TTL** — `enrich.maxAge: "30d"`, re-enrich rows older than that. Simple and predictable; costs calls on a schedule regardless of whether anything changed.
4. **Make `--full-refresh` mean it** — clear the stamp as part of a full refresh, with a confirmation prompt showing the record count. Matches what the flag name promises; the prompt keeps the cost from being a surprise.

(2) is probably the right default with (1) as the escape hatch, but this is worth a decision rather than a straight pick.

## Related

- Documented as a known gap in #167 — `one guide sync` and `skills/one/SKILL.md` now tell users that re-running a sync will not refresh detail content and that deleting the mirror is the current workaround.
- Also noted there and worth folding into the same fix: `--no-memory` does not stop the enrich phase from mirroring into the memory store (`runner.ts` passes `profile` into the enrich context unconditionally). Pinned by a test named `PRE-EXISTING GAP: …` so it can't drift unnoticed.

**Comment by ayushsingh82** [comment]
Read through this and the referenced code paths — agree (2), fingerprint-driven invalidation, should be the default, with (1) as the escape hatch rather than a competing option. A few reasons:

- **(2) matches user intent by default.** Re-enriching only when a designated list field actually moved (`historyId` for Gmail, `updated_at` for Fathom) means the common case — nothing changed upstream — costs zero extra detail calls. That's the behavior people assume they already have, given the flag is called `--full-refresh`.
- **(1) is a strict subset of the work (2) needs anyway.** Both require a code path that clears `_enriched_at` before phase 2 runs; (2) just adds the "should I clear it" decision on top via `enrich.invalidateOn`. So `--re-enrich` isn't wasted work if (2) lands later — it's the immediate, low-risk fix that unblocks the "there is currently no way to re-enrich" problem today, while the fingerprint logic gets designed properly.
- **Graceful fallback matters for the profiles without a good fingerprint field.** For any profile lacking a sensible `invalidateOn` path, (2) should simply behave as it does today (never auto re-enrich) rather than erroring or guessing — keeps the feature additive instead of a breaking behavior change for profiles that don't opt in.

Suggested sequencing: ship `--re-enrich` first (small, self-contained, immediately useful), then layer `enrich.invalidateOn` with the Gmail/Fathom defaults on top so most users never need to reach for the flag manually.

Happy to take a pass at the `--re-enrich` flag first if that sequencing sounds right — it's the smaller, lower-risk piece and doesn't block whatever gets decided for the fingerprint default.

cc @siddharth-bhansali for a decision on sequencing, since the writeup called this out as worth a deliberate choice rather than a drive-by pick.
